biblioteca/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('livros.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/livros/models.py
from django.db import models
from django.contrib.auth.models import User

class Autor(models.Model):
    SEXO = (
        (1, 'Masculino'),
        (2, 'Feminino')
    )

    nome = models.CharField(max_length=150)
    data_nasc = models.DateField()
    nacionalidade = models.CharField(max_length=50)
    sexo = models.IntegerField(choices=SEXO)

    def __str__(self):
        return self.nome

class Editora(models.Model):
    nome = models.CharField(max_length=150)
    cidade = models.CharField(max_length=150)
    estado = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class Livro(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    genero = models.CharField(max_length=50)
    qtd_paginas = models.IntegerField()
    ano_pub = models.IntegerField()
    resenha = models.TextField()
    autor = models.ManyToManyField(Autor)
    editora = models.ForeignKey(Editora, on_delete=models.CASCADE)
    publicado = models.BooleanField(default=False)
    capa_livro = models.ImageField(upload_to='capas/%d/%m/%Y', blank=True)

    def __str__(self):
        return self.nome

templates/autores/cria_autor.html
{% extends '../template.html' %}
{% load static %}
{% block conteudo %}
    <div class="row">
        <div class="col-12">
            <div align="center">
                <h2>Criar Autor</h2>
            </div>
        </div>
    </div>
    {% include 'partils/_alertas.html' %}
    <form action="{% url 'cria_autor' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12 col-lg-6 mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" class="form-control" id="nome" name="nome" required>
            </div>
            <div class="col-12 col-lg-6 mb-3">
                <label for="data_nasc" class="form-label">Data de nascimento</label>
                <input type="date" class="form-control" id="data_nasc" name="data_nasc" required>
            </div>
            <div class="col-12 col-lg-6 mb-3">
                <label for="nacionalidade" class="form-label">Nacionalidade</label>
                <input type="text" class="form-control" id="nacionalidade" name="nacionalidade" required>
            </div>
            <div class="col-12 col-lg-6 mb-3">
                <label for="sexo" class="form-label">Sexo</label>
                <select class="form-select" aria-label="Default select example" id="sexo" name="sexo" required>
                    <option value="1">Masculino</option>
                    <option value="2">Feminino</option>
                </select>
            </div>
            <div class="col-12 col-lg-12">
                <button class="btn btn-primary" type="submit">Cadastrar</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/autores/edita_autor.html
{% extends '../template.html' %}
{% load static %}
{% block conteudo %}
    <div class="row">
        <div class="col-12">
            <div align="center">
                <h2>Editar Autor</h2>
            </div>
        </div>
    </div>
    {% include 'partils/_alertas.html' %}
    <form action="{% url 'atualiza_autor' %}" method="post">
        {% csrf_token %}
        <input type="hidden" value="{{ autor.id }}" name="autor_id">
        <div class="row">
            <div class="col-12 col-lg-6 mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" class="form-control" id="nome" name="nome" value="{{ autor.nome }}" required>
            </div>
            <div class="col-12 col-lg-6 mb-3">
                <label for="data_nasc" class="form-label">Data de nascimento</label>
                <input type="date" class="form-control" id="data_nasc" name="data_nasc" value="{{ autor.data_nasc|date:'Y-m-d' }}" required>
            </div>
            <div class="col-12 col-lg-6 mb-3">
                <label for="nacionalidade" class="form-label">Nacionalidade</label>
                <input type="text" class="form-control" id="nacionalidade" name="nacionalidade" value="{{ autor.nacionalidade }}" required>
            </div>
            <div class="col-12 col-lg-6 mb-3">
                <label for="sexo" class="form-label">Sexo</label>
                <select class="form-select" aria-label="Default select example" id="sexo" name="sexo" required>
                    {% if autor.sexo == 1 %}
                        <option value="1" selected>Masculino</option>
                        <option value="2">Feminino</option>
                    {% else %}
                        <option value="1">Masculino</option>
                        <option value="2" selected>Feminino</option>
                    {% endif %}
                </select>
            </div>
            <div class="col-12 col-lg-12">
                <button class="btn btn-primary" type="submit">Atualizar</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/autores/lista.html
{% extends 'template.html' %}
{% load static %}
{% block conteudo %}
			<div class="page-header text-center py-3">
            	<h1>Autores</h1>
        	</div>
            {% include 'partils/_alertas.html' %}
            <table class="table caption-top">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Nome</th>
                        <th scope="col">Data de nascimento</th>
                        <th scope="col">Nacionalidade</th>
                        <th scope="col">Sexo</th>
                        <th scope="col">Editar</th>
                        <th scope="col">Excluir</th>
                    </tr>
                </thead>
                {% for autor in autores %}
                <tbody>
                    <tr>
                        <td>{{ autor.nome }}</td>
                        <td>{{ autor.data_nasc }}</td>
                        <td>{{ autor.nacionalidade }}</td>
                        <td>{{ autor.get_sexo_display }}</td>
                        <td><a href="{% url 'edita_autor' autor.id %}" class="btn btn-primary">Editar</a></td>
                        <td><a href="{% url 'deleta_autor' autor.id %}" class="btn btn-danger">Deletar</a></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
{% endblock %}